# Aula 1: Introdução ao Numpy e Pandas

## Listas

### Basics

In [ ]:
#define list
list()

In [ ]:
a = [1, 2, 3, 4, 5, 6]
lista = []

In [ ]:
a

In [ ]:
va = list([1])
va

In [ ]:
# [0, 5[

list(range(0, 5))

In [ ]:
list(range(0, 5, 2))

In [ ]:
#add new value to the list
a.append(7)

In [ ]:
a

In [ ]:
a.insert(1, 8)
a

In [ ]:
[1, 2, 3, 4, 5]

In [ ]:
a

In [ ]:
#delete element from the list
a.remove(1)

In [ ]:
a

In [ ]:
del(a[1])

In [ ]:
a

In [ ]:
a.pop()

In [ ]:
a

In [ ]:
a.pop(1)

In [ ]:
a

### Fila -> First in, First Out

### Pilha -> First in, Last out

In [ ]:
a

In [ ]:
#find element index

a.index(8)


In [ ]:
#del element using index

In [ ]:
a = list(range(0, 100, 3))
a[0] = 66

In [ ]:
a

In [ ]:
del a[a.index(66)]

In [ ]:
a

In [ ]:
#check if element is in the list

In [ ]:
3 in a

In [ ]:
#tipo de objeto

In [ ]:
type(a)

In [ ]:
a[1] = 3

In [ ]:
a

In [ ]:
a.remove(3)

In [ ]:
a

### Question 1
 Remove all 1 from the list
 
 [1, 1, 1, 2, 3, 4, 5, 1, 2, 1]

In [ ]:
lista = [1, 1, 1, 2, 3, 4, 5, 1, 2, 1]

In [ ]:
while 1 in lista:
    lista.remove(1)

In [ ]:
lista

In [ ]:
lista_nova = [item for item in lista if item != 1]

lista_nova

In [ ]:
for i in range(len(lista)):
    print(i)
    print(lista, len(lista))
    if lista[i]==1:
        lista.pop(i)

### List comprehension

In [ ]:
# lista com 10 zeros
lista = [0, 0, 0,0,0, 0,0, 0,0,0]
lista

In [ ]:
lista = []
for i in range(10):
    lista.append(0)
lista

In [ ]:
[(i, 0) for i in range(10)]

In [ ]:
[0 for item in range(10)]
    

In [ ]:
# comprehension
lista = [0 for item in range(0, 10)]
lista

In [ ]:
tuple((item for item in range(0, 10)))

In [ ]:
[]
[0,_]
[0, 0]
[0, 0, 0, _]
[0, 0, 0, 0]
[0, 0, 0, 0, _, _]

[0, 0, 0, 0, 0, 0 ..., 0]


In [ ]:
#somar 1 em todos elementos da lista
lista

In [ ]:
[item+1 for item in lista]

In [ ]:
#somar as metades da lista e criar uma lista nova com 5 elementos

In [ ]:
lista = list(range(10))
lista

In [ ]:
[item+item for item in lista[0:4]]

In [ ]:
lista1 = lista[0:5]
lista2 = lista[5:10]


In [ ]:
lista1 + lista2

In [ ]:
[lista1[i]+lista2[i] for i in range(0, 5)]

In [ ]:
[lista1[i]+lista2[i] for i in range(len(lista1))]

In [ ]:
[l1+l2 for l1, l2 in zip(lista1,lista2)]

In [ ]:
list(zip(lista1,lista2))

In [ ]:
#copiar lista

In [ ]:
lista_nova = lista
lista_nova

In [ ]:
lista_nova.append(10)

In [ ]:
id(lista_nova)

In [ ]:
id(lista)

In [ ]:
lista_nova = lista[:] 
# lista_nova = lista.copy()

In [ ]:
# lista_nova.append(11)
lista_nova

In [ ]:
lista

In [ ]:
#Funçoes um pouco mais avançadas de lista
#lambda
#map
#zip
#enumerate
#filter
#next
#reduce

In [ ]:
def soma_um(numero):
    return numero+1

soma_um(4545)

In [ ]:
def soma_um(numero): return numero+1

soma_um(4545)

In [ ]:
def soma_ate_n(numero, n):
    if n == 0:
        return numero
    else:
        return numero+soma_ate_n(numero, n-1)
    
soma_ate_n(4, 2)

In [ ]:
soma_dois = lambda numero: numero+2

soma_dois(54)

In [ ]:
lista = list(range(10))
lista

In [ ]:
for i in range(len(lista)):
    lista[i] = lista[i]+1
lista

In [ ]:
list(map(lambda numero: numero*10, lista))

In [ ]:
list(zip(lista, lista[:8]))

In [ ]:
for i, j in zip(lista, lista[1:]):
    print(f'diferença é: {j-i} - {i}, {j}')

In [ ]:
for elem in zip(lista, lista[1:], lista[2:]):
    print(elem, elem[0], '-' , elem[1])

In [ ]:
soma_um(1,2, 3, 4, 5)

In [ ]:
print('Lucas', 'Joao', 4, 5)

In [ ]:
def soma_numeros(*numeros):
    print(numeros)
    
soma_numeros(1, 2, 3, 10)

In [ ]:
soma_numeros()

In [ ]:
def imprime(**var):
    print(var)
    
imprime(numero=1, nome='Lucas', idade=29)

In [ ]:
lista

In [ ]:
list(enumerate(lista))

In [ ]:
for idx, elem in enumerate(lista):
    print(idx, elem)

In [ ]:
list(enumerate(lista))

In [ ]:
#filter
#next
#reduce

In [ ]:
list(filter(lambda numero: numero%2 == 1,lista))

In [ ]:
lista_palavras = ['', 'Bola..', '', '', 'Japão.', '', '.', '.Coruja', '', 'Futebol']

In [ ]:
'.Lucas Batista.  .'.strip('.').strip().strip('.')

In [ ]:
list(filter(lambda x: x!='',map(lambda palavra: palavra.strip('.'), lista_palavras)))

In [ ]:
lista_filtrada = filter(None, map(lambda palavra: palavra.strip('.'), lista_palavras))
lista_filtrada

In [ ]:
filter(map(lambda palavra: palavra.strip('.'), lista_palavras), lambda x: x!='')

In [47]:
lista_palavras = ['', 'Bola..', '', '', 'Japão.', '', '.', '.Coruja', '', 'Futebol']

In [52]:
lista_filtrada = filter(None, map(lambda palavra: palavra.strip('.'), lista_palavras))

In [40]:
next(lista_filtrada, 'Lista Vazia')

'Lista Vazia'

In [42]:
lista = list(range(10))
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [45]:
#reduce
from functools import reduce

reduce(lambda x, y: x+y, lista)

45

In [53]:
l = list(lista_filtrada)

In [56]:
l

['Bola', 'Japão', 'Coruja', 'Futebol']

In [58]:
reduce(lambda x, y: x if x<y else y, l)

'Bola'

In [64]:
'A' < 'AM'

True

In [65]:
ord('a')

97

In [66]:
ord('A')

65

In [ ]:
# homework
# https://www.youtube.com/watch?v=Zv4ge83Qz8I&t=951s

## Numpy

In [68]:
import numpy as np

Numpy é uma biblioteca das principais bibliotecas do Python, devido a sua grande velocidade e eficiência ele é extremamente utilizada para computação científica e analise de dados. Esta fama se da principalmente a estrutura chamada [numpy array](https://docs.scipy.org/doc/numpy/reference/arrays.html), um forma eficiente de guardar e manipular matrizes, que serve como base para as tabelas que iremos utilizar.

In [67]:
# criando listas numpy a partir de listas do python
lista = [1, 2, 3, 4, 5]
lista

[1, 2, 3, 4, 5]

In [69]:
array = np.array(lista)
array

array([1, 2, 3, 4, 5])

In [71]:
[0 for i in range(10)]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [72]:
#Criando array zeros numpy
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [73]:
#Criando array 1 
[1 for i in range(10)]

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [74]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Multiplicação de Listas vs np.Array

In [76]:
uns = [1 for i in range(10)]


In [78]:
[5*i for i in uns]

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]

In [80]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [81]:
ones*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [82]:
#Criando array de um numero qualquer
(np.ones(10) + 5)/3*2

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

In [83]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
#Criando array com sequencia
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
#Criando array com saltos
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [90]:
#Array espaçado, os dois primeiros numeros são o intervalo, o terceiro e numero de valores 
[np.arange(0, 2.1, 0.1)]

[array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
        1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])]

In [95]:
n = 20
x = 2/n
[x*i for i in range(n+1)]

[0.0,
 0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6000000000000001,
 0.7000000000000001,
 0.8,
 0.9,
 1.0,
 1.1,
 1.2000000000000002,
 1.3,
 1.4000000000000001,
 1.5,
 1.6,
 1.7000000000000002,
 1.8,
 1.9000000000000001,
 2.0]

In [98]:
np.linspace(0, 2, 10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [99]:
from numpy import random

#Criando array com valores aleatorios
random.rand(10)

array([0.74524298, 0.64157724, 0.93844814, 0.53282787, 0.61159475,
       0.24624227, 0.73147821, 0.72193616, 0.48905397, 0.88605545])

In [100]:
# aleatorio inteiro (10 itens de 0 a 100)
random.randint(0, 100, 10)

array([41, 47, 26, 46, 71, 60, 37, 43, 38, 72])

In [103]:
import random

np.array(random.sample(range(100), 10))

array([36, 22, 72, 60, 23, 11,  4, 17, 62, 74])

In [107]:
random.seed()

### Indexação

In [108]:
lista = list(range(10))
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [109]:
lista[3:]

[3, 4, 5, 6, 7, 8, 9]

In [110]:
lista[::-1]

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [111]:
lista[1: 5]

[1, 2, 3, 4]

In [114]:
lista[3:6:-1]

[]

In [115]:
lista[6:3:-1]

[6, 5, 4]

In [116]:
lista[-4:-5:-6]

[6]

In [117]:
lista[5:2:-1]

[5, 4, 3]

In [123]:
array

array([1, 2, 3, 4, 5])

In [124]:
array[1::3]

array([2, 5])

In [129]:
s = slice(1,5, 2)

In [130]:
array[s]

array([2, 4])

### Operações matemáticas

In [135]:
array

array([1, 2, 3, 4, 5])

### Operações com Arrays

In [133]:
#adição
array + 1

array([2, 3, 4, 5, 6])

In [134]:
#multiplicação
array * 2

array([ 2,  4,  6,  8, 10])

In [136]:
#produto entre dois arrays
array * array

array([ 1,  4,  9, 16, 25])

In [137]:
array @ array

55

In [138]:
# divisão
array / 4

array([0.25, 0.5 , 0.75, 1.  , 1.25])

In [139]:
array2 = [0, 1, 1, 1, 1]

In [141]:
array3 = array/array2

<ipython-input-141-a006ec1cb2a5>:1: RuntimeWarning: divide by zero encountered in true_divide
  array3 = array/array2


In [142]:
#filtro
array3

array([inf,  2.,  3.,  4.,  5.])

In [147]:
array3 != np.inf

array([False,  True,  True,  True,  True])

In [148]:
array3[array3 != np.inf]

array([2., 3., 4., 5.])

In [151]:
np.array(list(filter(lambda x: x!=np.inf and x%2==0, array3)))

array([2., 4.])

In [152]:
array3%2==0

<ipython-input-152-4d70061f1281>:1: RuntimeWarning: invalid value encountered in remainder
  array3%2==0


array([False,  True, False,  True, False])

In [162]:
array3[(array3 != np.inf) & (array3%2==0)]

<ipython-input-162-723b79b458c1>:1: RuntimeWarning: invalid value encountered in remainder
  array3[(array3 != np.inf) & (array3%2==0)]


array([2., 4.])

1100 & 
0101

0100

In [159]:
array3[(array3 != np.inf)][(array3[(array3 != np.inf)]%2==0)]

array([2., 4.])

In [164]:
#concatenate
np.concatenate((array, array2))

array([1, 2, 3, 4, 5, 0, 1, 1, 1, 1])

### Operações em arrays

### Problema 1:
Somar 2 **Listas** aleatórias de tamanhos iguais - Retorno deve conter uma lista

In [168]:
import random
lista1 = [random.randrange(0, 10, 1) for i in range(10)]
lista2 = [random.randrange(0, 10, 1) for i in range(10)]


In [170]:
lista1

[5, 1, 3, 1, 7, 7, 0, 5, 5, 3]

In [171]:
lista2

[4, 4, 5, 5, 9, 5, 2, 1, 1, 2]

In [169]:
for i,j in zip(lista1, lista2):
    lista3=[i+j for i,j in zip(lista1,lista2)]
print(lista3)

[9, 5, 8, 6, 16, 12, 2, 6, 6, 5]


In [172]:
import random
lista1 = random.sample(range(100), 10)
lista2 = random.sample(range(100), 10)
print(lista1, lista2, sep='\n')

[39, 66, 33, 69, 84, 93, 58, 91, 62, 31]
[6, 90, 55, 9, 62, 44, 66, 1, 86, 39]


In [175]:
#numpy
import numpy as np
array1 = np.array(lista1)
array2 = np.array(lista2)
array3 = array1+array2
list(array3)

[45, 156, 88, 78, 146, 137, 124, 92, 148, 70]

In [176]:
array3.tolist()

[45, 156, 88, 78, 146, 137, 124, 92, 148, 70]

In [177]:
array = np.array(lista1)+np.array(lista2)
print(array.tolist())

[45, 156, 88, 78, 146, 137, 124, 92, 148, 70]


In [178]:
[lista1[i]+lista2[i] for i in range(len(lista1))]

[45, 156, 88, 78, 146, 137, 124, 92, 148, 70]

In [179]:
#list comprehension + enumerate
[x+lista2[i] for i, x in enumerate(lista1)]

[45, 156, 88, 78, 146, 137, 124, 92, 148, 70]

In [180]:
#list comprehension + zip
[x+y for x, y in zip(lista1, lista2)]

[45, 156, 88, 78, 146, 137, 124, 92, 148, 70]

In [181]:
#map + lambda
list(map(lambda x,y: x+y, lista1, lista2))

[45, 156, 88, 78, 146, 137, 124, 92, 148, 70]

### problema 2
Somar 2 Arrays de tamanhos diferentes - Retorno deve conter um array

***Tomar cuidado ao fazer operações com arrays de tamanhos diferentes***

Ex: array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) + array([1, 1, 1, 1, 1]) = array(2, 3, 4, 5, 6, 6, 7, 8, 9, 10)

In [182]:
lista1 = np.random.randint(0,100,10)
lista2 = np.random.randint(0,100,5)
print(lista1, type(lista1))
print(lista2, type(lista2))

[56 54 15 74  4 64 70 15 23 10] <class 'numpy.ndarray'>
[33 28 99 82 97] <class 'numpy.ndarray'>


In [183]:
lista1+lista2

ValueError: operands could not be broadcast together with shapes (10,) (5,) 

In [184]:
lista1[0:len(lista2)]+lista2

array([ 89,  82, 114, 156, 101])

In [189]:
lista1.shape

(10,)

In [185]:
lista1+np.concatenate((lista2, np.zeros( lista1.shape[0] - lista2.shape[0] )))

array([ 89.,  82., 114., 156., 101.,  64.,  70.,  15.,  23.,  10.])

In [194]:
np.ones((10, 1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [193]:
np.ones((10, 1)).shape

(10, 1)

In [192]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Métodos

In [198]:
arr = np.random.randint(0,100,10)
arr

array([42,  9, 93, 88, 83, 33, 46, 33, 95, 40])

In [199]:
#maior valor
arr.max()

95

In [200]:
#index do maior valor
arr.argmax()

8

In [201]:
#menor valor
arr.min()

9

In [202]:
#index do menor valor
arr.argmin()

1

In [203]:
#soma de todos os items
arr.sum()

562

In [204]:
#media
arr.mean()

56.2

In [205]:
#desvio padrão
arr.std()

29.08882947112173

In [212]:
#ordenar a lista
sorted(arr, reverse=True)

[95, 93, 88, 83, 46, 42, 40, 33, 33, 9]

In [207]:
arr

array([42,  9, 93, 88, 83, 33, 46, 33, 95, 40])

In [227]:
arr.sort()

In [228]:
arr

array([ 9, 33, 33, 40, 42, 46, 83, 88, 93, 95])

In [230]:
## Aleatorizando o array

arr = np.random.permutation(arr)

## ou
random.shuffle(arr)

arr

array([33, 95, 83, 93, 40,  9, 46, 33, 88, 42])

In [236]:
#Trocando o tipo dos dados nas lista
arr.astype(float)

array([33., 95., 83., 93., 40.,  9., 46., 33., 88., 42.])

In [237]:
arr

array([33, 95, 83, 93, 40,  9, 46, 33, 88, 42])

In [242]:
# Valores únicos
arr = np.array([1, 1, 1, 3, 4,4, 4, 4,  5])
np.unique(arr)

array([1, 3, 4, 5])

In [243]:
np.unique(arr, return_counts=True)

(array([1, 3, 4, 5]), array([3, 1, 4, 1]))

In [246]:
#moda
values, count = np.unique(arr, return_counts=True)

In [249]:
values[count.argmax()]

4

In [250]:
import statistics

statistics.mode(arr)

4

### Matriz

In [251]:
#Criando matriz
matriz = np.matrix('1 2 1;3 4 1;5 6 1')
matriz

matrix([[1, 2, 1],
        [3, 4, 1],
        [5, 6, 1]])

In [257]:
np.matrix([[1, 2], [3, 4], [5, 6]])

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [260]:
#Matriz de zeros
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [261]:
#Matriz de 1's
np.ones((3, 1))

array([[1.],
       [1.],
       [1.]])

In [263]:
#eye - Matriz identidade
np.eye(4, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Operações

In [265]:
arr = np.arange(0, 20, 2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [266]:
arr.shape

(10,)

In [268]:
# Redimensionamento
matrix  = arr.reshape(5, 2)
matrix

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [269]:
matrix.shape

(5, 2)

In [271]:
#Matriz Transposta
matrix.transpose()

array([[ 0,  4,  8, 12, 16],
       [ 2,  6, 10, 14, 18]])

In [273]:
matrix.T.shape

(2, 5)

In [289]:
#concatenaçäo
np.concatenate((np.ones((5, 1)), matrix), axis=1)

array([[ 1.,  0.,  2.],
       [ 1.,  4.,  6.],
       [ 1.,  8., 10.],
       [ 1., 12., 14.],
       [ 1., 16., 18.]])

In [291]:
#hstack
np.hstack((np.ones((5, 2)), matrix))

array([[ 1.,  1.,  0.,  2.],
       [ 1.,  1.,  4.,  6.],
       [ 1.,  1.,  8., 10.],
       [ 1.,  1., 12., 14.],
       [ 1.,  1., 16., 18.]])

In [292]:
#vstack
np.vstack((np.ones(2), matrix))

array([[ 1.,  1.],
       [ 0.,  2.],
       [ 4.,  6.],
       [ 8., 10.],
       [12., 14.],
       [16., 18.]])

In [294]:
matrix

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [296]:
#indexação matriz
matrix[2:,1:]

array([[10],
       [14],
       [18]])

In [299]:
np.ones((5, 2, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

### Problema 3: 

Criar uma matriz 10x2 onde na primeira coluna estejam os valores de [1..10] e a segunda coluna seja preenchida com zeros

In [300]:
lista = []
for i in range(1, 11):
    lista.append([i, 0])
np.array(lista)

array([[ 1,  0],
       [ 2,  0],
       [ 3,  0],
       [ 4,  0],
       [ 5,  0],
       [ 6,  0],
       [ 7,  0],
       [ 8,  0],
       [ 9,  0],
       [10,  0]])

### Máscaras

In [ ]:
#Criando array com sequencia


In [ ]:
#Numeros pares


In [ ]:
#Aplicando a mascara maior que 2


In [ ]:
#mascaras com mais de 1 condição


## Pandas

### Series

`Series` representam as colunas das tabelas, guardando seu conteúdo com numpy arrays, porem neste caso cada array tem um index, que permite acessar o conteúdo das series como um similar a um dicionário python. além disso essa classe conta com alguns métodos mais avançados que o numpy array.

In [ ]:
#utilizando um lista simples


In [ ]:
#Acessando dados como uma lista


In [ ]:
#indexação

In [ ]:
#Series com index


In [ ]:
#acessando index 'a' da serie


In [ ]:
#acessando index 'a' e 'b' da serie


In [ ]:
#Series com dicionarios


In [ ]:
#operações com series


In [ ]:
#unique


In [ ]:
#Contando valores


In [ ]:
#Contando valores em porcentagem


In [ ]:
#isin - Para filtar valores

### Dataframe

E por ultimo temos a estrutura DataFrame, esta será nossa tabela, representada por um dicionário de series com o mesmo index.

In [ ]:
# acessando coluna 'x', retornando uma serie


In [ ]:
# acessando colunas 'x' e 'y', retornando um dataframe


In [ ]:
#pegando ponto


In [ ]:
#Pegando linha


In [ ]:
#Pegando linha por numero


In [ ]:
#pegando linha e coluna


In [ ]:
#nova coluna 


In [ ]:
#remove mas não salva


In [ ]:
#remove e salva


In [ ]:
#retirando linhas


In [ ]:
#Seleções através de condições


In [ ]:
#utilizando condição como mascara para um novo dataFrame


In [ ]:
#porem não salva


In [ ]:
#retira a linha do y que tem um item menor que 0


In [ ]:
#Mesma operação de cima porem so retorna o linha z


In [ ]:
#resetando index


In [ ]:
#resetando index sem manter o index antigo


In [ ]:
#reordenando as colunas


In [ ]:
#Alterando o nome das colunas


In [ ]:
#criando novo index


**indices multiplos**

#### Concats e merges

#### Importando dados