# Aula 1: Introdução ao Numpy e Pandas

## Listas

### Basics

In [ ]:
#define list
list()

In [ ]:
a = [1, 2, 3, 4, 5, 6]
lista = []

In [ ]:
a

In [ ]:
va = list([1])
va

In [ ]:
# [0, 5[

list(range(0, 5))

In [ ]:
list(range(0, 5, 2))

In [ ]:
#add new value to the list
a.append(7)

In [ ]:
a

In [ ]:
a.insert(1, 8)
a

In [ ]:
[1, 2, 3, 4, 5]

In [ ]:
a

In [ ]:
#delete element from the list
a.remove(1)

In [ ]:
a

In [ ]:
del(a[1])

In [ ]:
a

In [ ]:
a.pop()

In [ ]:
a

In [ ]:
a.pop(1)

In [ ]:
a

### Fila -> First in, First Out

### Pilha -> First in, Last out

In [ ]:
a

In [ ]:
#find element index

a.index(8)


In [ ]:
#del element using index

In [ ]:
a = list(range(0, 100, 3))
a[0] = 66

In [ ]:
a

In [ ]:
del a[a.index(66)]

In [ ]:
a

In [ ]:
#check if element is in the list

In [ ]:
3 in a

In [ ]:
#tipo de objeto

In [ ]:
type(a)

In [ ]:
a[1] = 3

In [ ]:
a

In [ ]:
a.remove(3)

In [ ]:
a

### Question 1
 Remove all 1 from the list
 
 [1, 1, 1, 2, 3, 4, 5, 1, 2, 1]

In [ ]:
lista = [1, 1, 1, 2, 3, 4, 5, 1, 2, 1]

In [ ]:
while 1 in lista:
    lista.remove(1)

In [ ]:
lista

In [ ]:
lista_nova = [item for item in lista if item != 1]

lista_nova

In [ ]:
for i in range(len(lista)):
    print(i)
    print(lista, len(lista))
    if lista[i]==1:
        lista.pop(i)

### List comprehension

In [ ]:
# lista com 10 zeros
lista = [0, 0, 0,0,0, 0,0, 0,0,0]
lista

In [ ]:
lista = []
for i in range(10):
    lista.append(0)
lista

In [ ]:
[(i, 0) for i in range(10)]

In [ ]:
[0 for item in range(10)]
    

In [ ]:
# comprehension
lista = [0 for item in range(0, 10)]
lista

In [ ]:
tuple((item for item in range(0, 10)))

In [ ]:
[]
[0,_]
[0, 0]
[0, 0, 0, _]
[0, 0, 0, 0]
[0, 0, 0, 0, _, _]

[0, 0, 0, 0, 0, 0 ..., 0]


In [ ]:
#somar 1 em todos elementos da lista
lista

In [ ]:
[item+1 for item in lista]

In [ ]:
#somar as metades da lista e criar uma lista nova com 5 elementos

In [ ]:
lista = list(range(10))
lista

In [ ]:
[item+item for item in lista[0:4]]

In [ ]:
lista1 = lista[0:5]
lista2 = lista[5:10]


In [ ]:
lista1 + lista2

In [ ]:
[lista1[i]+lista2[i] for i in range(0, 5)]

In [ ]:
[lista1[i]+lista2[i] for i in range(len(lista1))]

In [ ]:
[l1+l2 for l1, l2 in zip(lista1,lista2)]

In [ ]:
list(zip(lista1,lista2))

In [ ]:
#copiar lista

In [ ]:
lista_nova = lista
lista_nova

In [ ]:
lista_nova.append(10)

In [ ]:
id(lista_nova)

In [ ]:
id(lista)

In [ ]:
lista_nova = lista[:] 
# lista_nova = lista.copy()

In [ ]:
# lista_nova.append(11)
lista_nova

In [ ]:
lista

In [ ]:
#Funçoes um pouco mais avançadas de lista
#lambda
#map
#zip
#enumerate
#filter
#next
#reduce

In [ ]:
def soma_um(numero):
    return numero+1

soma_um(4545)

In [ ]:
def soma_um(numero): return numero+1

soma_um(4545)

In [ ]:
def soma_ate_n(numero, n):
    if n == 0:
        return numero
    else:
        return numero+soma_ate_n(numero, n-1)
    
soma_ate_n(4, 2)

In [ ]:
soma_dois = lambda numero: numero+2

soma_dois(54)

In [ ]:
lista = list(range(10))
lista

In [ ]:
for i in range(len(lista)):
    lista[i] = lista[i]+1
lista

In [ ]:
list(map(lambda numero: numero*10, lista))

In [ ]:
list(zip(lista, lista[:8]))

In [ ]:
for i, j in zip(lista, lista[1:]):
    print(f'diferença é: {j-i} - {i}, {j}')

In [ ]:
for elem in zip(lista, lista[1:], lista[2:]):
    print(elem, elem[0], '-' , elem[1])

In [ ]:
soma_um(1,2, 3, 4, 5)

In [ ]:
print('Lucas', 'Joao', 4, 5)

In [ ]:
def soma_numeros(*numeros):
    print(numeros)
    
soma_numeros(1, 2, 3, 10)

In [ ]:
soma_numeros()

In [ ]:
def imprime(**var):
    print(var)
    
imprime(numero=1, nome='Lucas', idade=29)

In [ ]:
lista

In [ ]:
list(enumerate(lista))

In [ ]:
for idx, elem in enumerate(lista):
    print(idx, elem)

In [ ]:
list(enumerate(lista))

In [ ]:
#filter
#next
#reduce

In [ ]:
list(filter(lambda numero: numero%2 == 1,lista))

In [ ]:
lista_palavras = ['', 'Bola..', '', '', 'Japão.', '', '.', '.Coruja', '', 'Futebol']

In [ ]:
'.Lucas Batista.  .'.strip('.').strip().strip('.')

In [ ]:
list(filter(lambda x: x!='',map(lambda palavra: palavra.strip('.'), lista_palavras)))

In [ ]:
lista_filtrada = filter(None, map(lambda palavra: palavra.strip('.'), lista_palavras))
lista_filtrada

In [ ]:
filter(map(lambda palavra: palavra.strip('.'), lista_palavras), lambda x: x!='')

In [47]:
lista_palavras = ['', 'Bola..', '', '', 'Japão.', '', '.', '.Coruja', '', 'Futebol']

In [52]:
lista_filtrada = filter(None, map(lambda palavra: palavra.strip('.'), lista_palavras))

In [40]:
next(lista_filtrada, 'Lista Vazia')

'Lista Vazia'

In [42]:
lista = list(range(10))
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [45]:
#reduce
from functools import reduce

reduce(lambda x, y: x+y, lista)

45

In [53]:
l = list(lista_filtrada)

In [56]:
l

['Bola', 'Japão', 'Coruja', 'Futebol']

In [58]:
reduce(lambda x, y: x if x<y else y, l)

'Bola'

In [64]:
'A' < 'AM'

True

In [65]:
ord('a')

97

In [66]:
ord('A')

65

In [ ]:
# homework
# https://www.youtube.com/watch?v=Zv4ge83Qz8I&t=951s

## Numpy

In [1]:
import numpy as np

Numpy é uma biblioteca das principais bibliotecas do Python, devido a sua grande velocidade e eficiência ele é extremamente utilizada para computação científica e analise de dados. Esta fama se da principalmente a estrutura chamada [numpy array](https://docs.scipy.org/doc/numpy/reference/arrays.html), um forma eficiente de guardar e manipular matrizes, que serve como base para as tabelas que iremos utilizar.

In [2]:
# criando listas numpy a partir de listas do python
lista = [1, 2, 3, 4, 5]
lista

[1, 2, 3, 4, 5]

In [3]:
array = np.array(lista)
array

array([1, 2, 3, 4, 5])

In [4]:
[0 for i in range(10)]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [5]:
#Criando array zeros numpy
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [73]:
#Criando array 1 
[1 for i in range(10)]

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Multiplicação de Listas vs np.Array

In [8]:
uns = [1 for i in range(10)]


In [9]:
uns

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [78]:
[5*i for i in uns]

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]

In [12]:
uns*2

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [80]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [81]:
ones*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [82]:
#Criando array de um numero qualquer
(np.ones(10) + 5)/3*2

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

In [83]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [85]:
#Criando array com sequencia
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
#Criando array com saltos
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [90]:
#Array espaçado, os dois primeiros numeros são o intervalo, o terceiro e numero de valores 
[np.arange(0, 2.1, 0.1)]

[array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
        1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])]

In [95]:
n = 20
x = 2/n
[x*i for i in range(n+1)]

[0.0,
 0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6000000000000001,
 0.7000000000000001,
 0.8,
 0.9,
 1.0,
 1.1,
 1.2000000000000002,
 1.3,
 1.4000000000000001,
 1.5,
 1.6,
 1.7000000000000002,
 1.8,
 1.9000000000000001,
 2.0]

In [14]:
np.linspace(0, 2, 20)

array([0.        , 0.10526316, 0.21052632, 0.31578947, 0.42105263,
       0.52631579, 0.63157895, 0.73684211, 0.84210526, 0.94736842,
       1.05263158, 1.15789474, 1.26315789, 1.36842105, 1.47368421,
       1.57894737, 1.68421053, 1.78947368, 1.89473684, 2.        ])

In [99]:
from numpy import random

#Criando array com valores aleatorios
random.rand(10)

array([0.74524298, 0.64157724, 0.93844814, 0.53282787, 0.61159475,
       0.24624227, 0.73147821, 0.72193616, 0.48905397, 0.88605545])

In [100]:
# aleatorio inteiro (10 itens de 0 a 100)
random.randint(0, 100, 10)

array([41, 47, 26, 46, 71, 60, 37, 43, 38, 72])

In [103]:
import random

np.array(random.sample(range(100), 10))

array([36, 22, 72, 60, 23, 11,  4, 17, 62, 74])

In [107]:
random.seed()

### Indexação

In [17]:
lista = list(range(10))
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [109]:
lista[3:]

[3, 4, 5, 6, 7, 8, 9]

In [18]:
lista[::-1]

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [111]:
lista[1: 5]

[1, 2, 3, 4]

In [19]:
lista[3:6:-1]

[]

In [16]:
lista[6:3:-1]

[5]

In [20]:
lista[-4:-5:-6]

[6]

In [117]:
lista[5:2:-1]

[5, 4, 3]

In [21]:
array

array([1, 2, 3, 4, 5])

In [124]:
array[1::3]

array([2, 5])

In [22]:
s = slice(1,5, 2)

In [130]:
array[s]

array([2, 4])

### Operações matemáticas

In [135]:
array

array([1, 2, 3, 4, 5])

### Operações com Arrays

In [133]:
#adição
array + 1

array([2, 3, 4, 5, 6])

In [134]:
#multiplicação
array * 2

array([ 2,  4,  6,  8, 10])

In [136]:
#produto entre dois arrays
array * array

array([ 1,  4,  9, 16, 25])

In [137]:
array @ array

55

In [138]:
# divisão
array / 4

array([0.25, 0.5 , 0.75, 1.  , 1.25])

In [139]:
array2 = [0, 1, 1, 1, 1]

In [141]:
array3 = array/array2

<ipython-input-141-a006ec1cb2a5>:1: RuntimeWarning: divide by zero encountered in true_divide
  array3 = array/array2


In [142]:
#filtro
array3

array([inf,  2.,  3.,  4.,  5.])

In [147]:
array3 != np.inf

array([False,  True,  True,  True,  True])

In [148]:
array3[array3 != np.inf]

array([2., 3., 4., 5.])

In [151]:
np.array(list(filter(lambda x: x!=np.inf and x%2==0, array3)))

array([2., 4.])

In [152]:
array3%2==0

<ipython-input-152-4d70061f1281>:1: RuntimeWarning: invalid value encountered in remainder
  array3%2==0


array([False,  True, False,  True, False])

In [162]:
array3[(array3 != np.inf) & (array3%2==0)]

<ipython-input-162-723b79b458c1>:1: RuntimeWarning: invalid value encountered in remainder
  array3[(array3 != np.inf) & (array3%2==0)]


array([2., 4.])

1100 & 
0101

0100

In [159]:
array3[(array3 != np.inf)][(array3[(array3 != np.inf)]%2==0)]

array([2., 4.])

In [164]:
#concatenate
np.concatenate((array, array2))

array([1, 2, 3, 4, 5, 0, 1, 1, 1, 1])

### Operações em arrays

### Problema 1:
Somar 2 **Listas** aleatórias de tamanhos iguais - Retorno deve conter uma lista

In [168]:
import random
lista1 = [random.randrange(0, 10, 1) for i in range(10)]
lista2 = [random.randrange(0, 10, 1) for i in range(10)]


In [170]:
lista1

[5, 1, 3, 1, 7, 7, 0, 5, 5, 3]

In [171]:
lista2

[4, 4, 5, 5, 9, 5, 2, 1, 1, 2]

In [169]:
for i,j in zip(lista1, lista2):
    lista3=[i+j for i,j in zip(lista1,lista2)]
print(lista3)

[9, 5, 8, 6, 16, 12, 2, 6, 6, 5]


In [172]:
import random
lista1 = random.sample(range(100), 10)
lista2 = random.sample(range(100), 10)
print(lista1, lista2, sep='\n')

[39, 66, 33, 69, 84, 93, 58, 91, 62, 31]
[6, 90, 55, 9, 62, 44, 66, 1, 86, 39]


In [175]:
#numpy
import numpy as np
array1 = np.array(lista1)
array2 = np.array(lista2)
array3 = array1+array2
list(array3)

[45, 156, 88, 78, 146, 137, 124, 92, 148, 70]

In [176]:
array3.tolist()

[45, 156, 88, 78, 146, 137, 124, 92, 148, 70]

In [177]:
array = np.array(lista1)+np.array(lista2)
print(array.tolist())

[45, 156, 88, 78, 146, 137, 124, 92, 148, 70]


In [178]:
[lista1[i]+lista2[i] for i in range(len(lista1))]

[45, 156, 88, 78, 146, 137, 124, 92, 148, 70]

In [179]:
#list comprehension + enumerate
[x+lista2[i] for i, x in enumerate(lista1)]

[45, 156, 88, 78, 146, 137, 124, 92, 148, 70]

In [180]:
#list comprehension + zip
[x+y for x, y in zip(lista1, lista2)]

[45, 156, 88, 78, 146, 137, 124, 92, 148, 70]

In [181]:
#map + lambda
list(map(lambda x,y: x+y, lista1, lista2))

[45, 156, 88, 78, 146, 137, 124, 92, 148, 70]

### problema 2
Somar 2 Arrays de tamanhos diferentes - Retorno deve conter um array

***Tomar cuidado ao fazer operações com arrays de tamanhos diferentes***

Ex: array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) + array([1, 1, 1, 1, 1]) = array(2, 3, 4, 5, 6, 6, 7, 8, 9, 10)

In [182]:
lista1 = np.random.randint(0,100,10)
lista2 = np.random.randint(0,100,5)
print(lista1, type(lista1))
print(lista2, type(lista2))

[56 54 15 74  4 64 70 15 23 10] <class 'numpy.ndarray'>
[33 28 99 82 97] <class 'numpy.ndarray'>


In [183]:
lista1+lista2

ValueError: operands could not be broadcast together with shapes (10,) (5,) 

In [184]:
lista1[0:len(lista2)]+lista2

array([ 89,  82, 114, 156, 101])

In [189]:
lista1.shape

(10,)

In [185]:
lista1+np.concatenate((lista2, np.zeros( lista1.shape[0] - lista2.shape[0] )))

array([ 89.,  82., 114., 156., 101.,  64.,  70.,  15.,  23.,  10.])

In [23]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [194]:
np.ones((10, 1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [193]:
np.ones((10, 1)).shape

(10, 1)

In [192]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Métodos

In [24]:
arr = np.random.randint(0,100,10)
arr

array([16, 34, 47, 96, 77, 31, 57, 11, 13, 55])

In [25]:
#maior valor
arr.max()

96

In [26]:
#index do maior valor
arr.argmax()

3

In [27]:
#menor valor
arr.min()

11

In [28]:
#index do menor valor
arr.argmin()

7

In [29]:
#soma de todos os items
arr.sum()

437

In [30]:
#media
arr.mean()

43.7

In [31]:
#desvio padrão
arr.std()

26.821819475941595

In [32]:
#ordenar a array
sorted(arr, reverse=True)

[96, 77, 57, 55, 47, 34, 31, 16, 13, 11]

In [33]:
arr

array([16, 34, 47, 96, 77, 31, 57, 11, 13, 55])

In [34]:
arr.sort()

In [35]:
arr

array([11, 13, 16, 31, 34, 47, 55, 57, 77, 96])

In [38]:
## Aleatorizando o array

arr = np.random.permutation(arr)

## ou
np.random.shuffle(arr)

arr

array([77, 13, 11, 47, 96, 34, 31, 57, 55, 16])

In [40]:
arr.dtype

dtype('int64')

In [37]:
#Trocando o tipo dos dados nas lista
arr.astype(float)

array([57., 55., 96., 16., 34., 47., 31., 11., 13., 77.])

In [237]:
arr

array([33, 95, 83, 93, 40,  9, 46, 33, 88, 42])

In [242]:
# Valores únicos
arr = np.array([1, 1, 1, 3, 4,4, 4, 4,  5])
np.unique(arr)

array([1, 3, 4, 5])

In [243]:
np.unique(arr, return_counts=True)

(array([1, 3, 4, 5]), array([3, 1, 4, 1]))

In [246]:
#moda
values, count = np.unique(arr, return_counts=True)

In [249]:
values[count.argmax()]

4

In [250]:
import statistics

statistics.mode(arr)

4

### Matriz

In [251]:
#Criando matriz
matriz = np.matrix('1 2 1;3 4 1;5 6 1')
matriz

matrix([[1, 2, 1],
        [3, 4, 1],
        [5, 6, 1]])

In [257]:
np.matrix([[1, 2], [3, 4], [5, 6]])

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [43]:
np.zeros((3, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [260]:
#Matriz de zeros
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [261]:
#Matriz de 1's
np.ones((3, 1))

array([[1.],
       [1.],
       [1.]])

In [263]:
#eye - Matriz identidade
np.eye(4, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [1]:
import numpy as np

In [8]:
(np.ones((3, 3))*5) @ np.eye(3, 3)

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

## M * $M^\(-1\)$ = I

#### Operações

In [44]:
arr = np.arange(0, 20, 2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [45]:
arr.shape

(10,)

In [46]:
# Redimensionamento
matrix  = arr.reshape(5, 2)
matrix

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [47]:
matrix.shape

(5, 2)

In [48]:
#Matriz Transposta
matrix.transpose()

array([[ 0,  4,  8, 12, 16],
       [ 2,  6, 10, 14, 18]])

In [50]:
matrix.T.shape

(2, 5)

In [52]:
#concatenaçäo
np.concatenate((np.ones((5, 1)), matrix), axis=1)

array([[ 1.,  0.,  2.],
       [ 1.,  4.,  6.],
       [ 1.,  8., 10.],
       [ 1., 12., 14.],
       [ 1., 16., 18.]])

In [55]:
np.concatenate((np.ones((5, 2)), matrix), axis=0)

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 0.,  2.],
       [ 4.,  6.],
       [ 8., 10.],
       [12., 14.],
       [16., 18.]])

In [53]:
#hstack
np.hstack((np.ones((5, 2)), matrix))

array([[ 1.,  1.,  0.,  2.],
       [ 1.,  1.,  4.,  6.],
       [ 1.,  1.,  8., 10.],
       [ 1.,  1., 12., 14.],
       [ 1.,  1., 16., 18.]])

In [59]:
#vstack
np.vstack((np.ones(2), matrix, np.zeros(2), matrix, matrix, matrix, matrix, matrix, matrix))

array([[ 1.,  1.],
       [ 0.,  2.],
       [ 4.,  6.],
       [ 8., 10.],
       [12., 14.],
       [16., 18.],
       [ 0.,  0.],
       [ 0.,  2.],
       [ 4.,  6.],
       [ 8., 10.],
       [12., 14.],
       [16., 18.],
       [ 0.,  2.],
       [ 4.,  6.],
       [ 8., 10.],
       [12., 14.],
       [16., 18.],
       [ 0.,  2.],
       [ 4.,  6.],
       [ 8., 10.],
       [12., 14.],
       [16., 18.],
       [ 0.,  2.],
       [ 4.,  6.],
       [ 8., 10.],
       [12., 14.],
       [16., 18.],
       [ 0.,  2.],
       [ 4.,  6.],
       [ 8., 10.],
       [12., 14.],
       [16., 18.],
       [ 0.,  2.],
       [ 4.,  6.],
       [ 8., 10.],
       [12., 14.],
       [16., 18.]])

In [294]:
matrix

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [296]:
#indexação matriz
matrix[2::1,1:]

array([[10],
       [14],
       [18]])

In [61]:
np.ones((5, 2, 4, 5, 4))

array([[[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

    

### Problema 3: 

Criar uma matriz 10x2 onde na primeira coluna estejam os valores de [1..10] e a segunda coluna seja preenchida com zeros

In [300]:
lista = []
for i in range(1, 11):
    lista.append([i, 0])
np.array(lista)

array([[ 1,  0],
       [ 2,  0],
       [ 3,  0],
       [ 4,  0],
       [ 5,  0],
       [ 6,  0],
       [ 7,  0],
       [ 8,  0],
       [ 9,  0],
       [10,  0]])

In [64]:
zeros = np.zeros((10,1))
zeros

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [67]:
arr = np.arange(1, 11).reshape(10, 1)
arr

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [68]:
zeros.vstack(arr)

AttributeError: 'numpy.ndarray' object has no attribute 'vstack'

In [71]:
np.hstack((arr, zeros))

array([[ 1.,  0.],
       [ 2.,  0.],
       [ 3.,  0.],
       [ 4.,  0.],
       [ 5.,  0.],
       [ 6.,  0.],
       [ 7.,  0.],
       [ 8.,  0.],
       [ 9.,  0.],
       [10.,  0.]])

In [72]:
np.vstack((arr, zeros))

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.]])

In [73]:
valores = np.array(range(1, 11))
valores

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
np.vstack((valores, np.zeros(10))).T

array([[ 1.,  0.],
       [ 2.,  0.],
       [ 3.,  0.],
       [ 4.,  0.],
       [ 5.,  0.],
       [ 6.,  0.],
       [ 7.,  0.],
       [ 8.,  0.],
       [ 9.,  0.],
       [10.,  0.]])

In [78]:
zeros

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [80]:
np.concatenate((arr, zeros), axis=1)

array([[ 1.,  0.],
       [ 2.,  0.],
       [ 3.,  0.],
       [ 4.,  0.],
       [ 5.,  0.],
       [ 6.,  0.],
       [ 7.,  0.],
       [ 8.,  0.],
       [ 9.,  0.],
       [10.,  0.]])

### Máscaras

In [81]:
from numpy import random

aleatorio = np.random.rand(10)
aleatorio

array([0.54813651, 0.46448919, 0.7058901 , 0.10505174, 0.34332784,
       0.52747452, 0.79078202, 0.90971057, 0.46297796, 0.13580861])

In [83]:
mask = aleatorio > 0.5
mask

array([ True, False,  True, False, False,  True,  True,  True, False,
       False])

In [84]:
aleatorio[mask]

array([0.54813651, 0.7058901 , 0.52747452, 0.79078202, 0.90971057])

In [85]:
~mask

array([False,  True, False,  True,  True, False, False, False,  True,
        True])

In [86]:
aleatorio[~mask]

array([0.46448919, 0.10505174, 0.34332784, 0.46297796, 0.13580861])

In [88]:
#Criando array com sequencia
arr = np.arange(0, 11)

In [89]:
#Numeros pares
arr[arr%2 == 0]

array([ 0,  2,  4,  6,  8, 10])

In [90]:
arr%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [92]:
arr[arr%2]

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [94]:
arr[arr[1:]%2]

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [97]:
arr[[1, 2, 3, 4, 0, 1]]

array([1, 2, 3, 4, 0, 1])

In [104]:
arr2 = np.arange(100, 200, 2)
arr2

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150,
       152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176,
       178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198])

In [105]:
arr2%2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [111]:
arr2[19]

138

In [113]:
arr2[arr2%3 == 2]

array([104, 110, 116, 122, 128, 134, 140, 146, 152, 158, 164, 170, 176,
       182, 188, 194])

In [115]:
#Aplicando a mascara maior que 2
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [116]:
#mascaras com mais de 1 condição
arr[(arr>2) & (arr%2==0)]

array([ 4,  6,  8, 10])

In [117]:
arr[arr>-1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [163]:
arr>2

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True])

In [118]:
arr[arr%2]

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [161]:
arr[[0, 1, 2, 3]]

array([0, 1, 2, 3])

## Pandas

In [119]:
!pip3 install pandas

### Series

`Series` representam as colunas das tabelas, guardando seu conteúdo com numpy arrays, porem neste caso cada array tem um index, que permite acessar o conteúdo das series como um similar a um dicionário python. além disso essa classe conta com alguns métodos mais avançados que o numpy array.

In [12]:
#utilizando um lista simples
import pandas as pd

In [121]:
minha_lista = [10, 20, 30]
minha_lista

[10, 20, 30]

In [122]:
minha_lista[1]

20

In [11]:
for idx, (v1, v2) in enumerate(zip([1, 2, 3], [4, 5, 6])):
    print(idx, v1, v2)

0 1 4
1 2 5
2 3 6


In [123]:
serie = pd.Series(minha_lista)
serie

0    10
1    20
2    30
dtype: int64

In [124]:
serie[1]

20

In [125]:
list(enumerate(minha_lista))

[(0, 10), (1, 20), (2, 30)]

In [126]:
list(zip(['a', 'b', 'c'], minha_lista))

[('a', 10), ('b', 20), ('c', 30)]

In [127]:
a = {'a':10, 'b':20, 'c':30}
a

{'a': 10, 'b': 20, 'c': 30}

In [128]:
a['a']

10

In [129]:
a.get('a')

10

In [131]:
#Acessando dados como uma lista
serie[1]

20

In [132]:
#indexação
serie[:2]

0    10
1    20
dtype: int64

20

In [133]:
#Series com index
labels = ['a', 'b', 'c', 'e']
lista = [10, 20, 30, 40]
serieLabel = pd.Series(data=lista, index=labels)
serieLabel

a    10
b    20
c    30
e    40
dtype: int64

In [137]:
#acessando index 'a' da serie
serieLabel['b']

20

In [138]:
serieLabel['a':'c']

a    10
b    20
c    30
dtype: int64

In [ ]:
#acessando index 'a' e 'b' da serie


In [140]:
#Series com dicionarios
alunos = {'nome':['Lucas', 'Roberto', 'Joao'], 'idade':[29, 10, 30]}
alunos

{'nome': ['Lucas', 'Roberto', 'Joao'], 'idade': [29, 10, 30]}

In [141]:
pd.Series(alunos)

nome     [Lucas, Roberto, Joao]
idade              [29, 10, 30]
dtype: object

In [144]:
#operações com series
dic1 = {"Brasil":10,"EUA":10,"Japão":10}
dic2 = {"Brasil":10,"Bolivia":10,"Japão":10}

serie1 = pd.Series(dic1)
serie2 = pd.Series(dic2)
serie1

Brasil    10
EUA       10
Japão     10
dtype: int64

In [143]:
serie2

Brasil     10
Bolivia    10
Japão      10
dtype: int64

In [145]:
serie1+serie2

Bolivia     NaN
Brasil     20.0
EUA         NaN
Japão      20.0
dtype: float64

In [149]:
#unique
np.unique(np.array([1, 1, 1, 1, 2, 43, 5, 7, 3, 2, 1]), return_counts=True)

(array([ 1,  2,  3,  5,  7, 43]), array([5, 2, 1, 1, 1, 1]))

In [13]:
serie1 = pd.Series(['a','b','c','a','d','e','c','a','e','d'])
serie1.unique()

array(['a', 'b', 'c', 'd', 'e'], dtype=object)

In [14]:
#Contando valores
serie1.value_counts()

a    3
d    2
e    2
c    2
b    1
dtype: int64

In [15]:
serie1.value_counts().sort_index()

a    3
b    1
c    2
d    2
e    2
dtype: int64

In [16]:
serie1.value_counts().sort_values()

b    1
d    2
e    2
c    2
a    3
dtype: int64

In [17]:
serie1.value_counts().sort_values(ascending=False)

a    3
d    2
e    2
c    2
b    1
dtype: int64

In [18]:
serie1.value_counts().sort_index(ascending=False)

e    2
d    2
c    2
b    1
a    3
dtype: int64

In [19]:
#Contando valores em porcentagem
serie1.value_counts().sort_index()/len(serie1)

a    0.3
b    0.1
c    0.2
d    0.2
e    0.2
dtype: float64

In [20]:
serie1.value_counts(normalize=True)

a    0.3
d    0.2
e    0.2
c    0.2
b    0.1
dtype: float64

In [158]:
#isin - Para filtar valores
mask = serie1.isin(['b', 'c'])

serie1[mask]

1    b
2    c
6    c
dtype: object

In [159]:
serie1

0    a
1    b
2    c
3    a
4    d
5    e
6    c
7    a
8    e
9    d
dtype: object

# VOLTAMOS AS 20:50 !!!!

### Dataframe

E por ultimo temos a estrutura DataFrame, esta será nossa tabela, representada por um dicionário de series com o mesmo index.

In [69]:
# NUNCA USAR SEED COM ARGUMENTO EM MODELOS DE PRODUÇÃO
# np.random.seed()
np.random.seed(42)

lista = np.random.randn(5, 3)
lista

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439],
       [ 0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783]])

In [70]:
lista[1, 1]

-0.23415337472333597

In [71]:
df = pd.DataFrame(lista)
df

0         1         2
0  0.496714 -0.138264  0.647689
1  1.523030 -0.234153 -0.234137
2  1.579213  0.767435 -0.469474
3  0.542560 -0.463418 -0.465730
4  0.241962 -1.913280 -1.724918

In [72]:
idx = ['a','b','c','d','e']
cols = ['x','y','z']
df = pd.DataFrame(data=lista, index=idx, columns=cols)
df

x         y         z
a  0.496714 -0.138264  0.647689
b  1.523030 -0.234153 -0.234137
c  1.579213  0.767435 -0.469474
d  0.542560 -0.463418 -0.465730
e  0.241962 -1.913280 -1.724918

In [73]:
# acessando coluna 'x', retornando uma serie
df['x']

a    0.496714
b    1.523030
c    1.579213
d    0.542560
e    0.241962
Name: x, dtype: float64

In [74]:
df['y']

a   -0.138264
b   -0.234153
c    0.767435
d   -0.463418
e   -1.913280
Name: y, dtype: float64

In [75]:
# acessando colunas 'x' e 'y', retornando um dataframe
df[['x', 'y']]

x         y
a  0.496714 -0.138264
b  1.523030 -0.234153
c  1.579213  0.767435
d  0.542560 -0.463418
e  0.241962 -1.913280

In [76]:
df[['y', 'x']]

y         x
a -0.138264  0.496714
b -0.234153  1.523030
c  0.767435  1.579213
d -0.463418  0.542560
e -1.913280  0.241962

In [77]:
#pegando ponto
df['z']['c']

-0.4694743859349521

In [78]:
df['z']

a    0.647689
b   -0.234137
c   -0.469474
d   -0.465730
e   -1.724918
Name: z, dtype: float64

In [79]:
df[['z', 'y']]

z         y
a  0.647689 -0.138264
b -0.234137 -0.234153
c -0.469474  0.767435
d -0.465730 -0.463418
e -1.724918 -1.913280

In [80]:
#Pegando linha
df.loc['c', ['z', 'y']]

z   -0.469474
y    0.767435
Name: c, dtype: float64

In [81]:
df.loc['c']

x    1.579213
y    0.767435
z   -0.469474
Name: c, dtype: float64

In [82]:
df.loc[['c']]

x         y         z
c  1.579213  0.767435 -0.469474

In [83]:
df.loc[:'c']

x         y         z
a  0.496714 -0.138264  0.647689
b  1.523030 -0.234153 -0.234137
c  1.579213  0.767435 -0.469474

In [84]:
df

x         y         z
a  0.496714 -0.138264  0.647689
b  1.523030 -0.234153 -0.234137
c  1.579213  0.767435 -0.469474
d  0.542560 -0.463418 -0.465730
e  0.241962 -1.913280 -1.724918

In [85]:
df.loc['c',['z','y']]

z   -0.469474
y    0.767435
Name: c, dtype: float64

In [86]:
df.loc[['c', 'd'],['x','y']]

x         y
c  1.579213  0.767435
d  0.542560 -0.463418

In [87]:
df[['z']]

z
a  0.647689
b -0.234137
c -0.469474
d -0.465730
e -1.724918

In [88]:
#Pegando linha por numero
df.iloc[3]

x    0.542560
y   -0.463418
z   -0.465730
Name: d, dtype: float64

In [89]:
#pegando linha e coluna
df.loc['c', ['x']]

x    1.579213
Name: c, dtype: float64

In [90]:
df.loc[['c'], ['x']]

x
c  1.579213

In [91]:
#nova coluna 
df['novo'] = df['x'] + df['y']
df

x         y         z      novo
a  0.496714 -0.138264  0.647689  0.358450
b  1.523030 -0.234153 -0.234137  1.288876
c  1.579213  0.767435 -0.469474  2.346648
d  0.542560 -0.463418 -0.465730  0.079142
e  0.241962 -1.913280 -1.724918 -1.671318

In [92]:
#remove mas não salva
df.drop('novo', axis=1)

x         y         z
a  0.496714 -0.138264  0.647689
b  1.523030 -0.234153 -0.234137
c  1.579213  0.767435 -0.469474
d  0.542560 -0.463418 -0.465730
e  0.241962 -1.913280 -1.724918

In [93]:
df

x         y         z      novo
a  0.496714 -0.138264  0.647689  0.358450
b  1.523030 -0.234153 -0.234137  1.288876
c  1.579213  0.767435 -0.469474  2.346648
d  0.542560 -0.463418 -0.465730  0.079142
e  0.241962 -1.913280 -1.724918 -1.671318

In [94]:
df.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [95]:
#remove e salva
# df = df.drop('novo', axis=1)
df.drop('novo', axis=1, inplace=True)

In [96]:
df

x         y         z
a  0.496714 -0.138264  0.647689
b  1.523030 -0.234153 -0.234137
c  1.579213  0.767435 -0.469474
d  0.542560 -0.463418 -0.465730
e  0.241962 -1.913280 -1.724918

In [97]:
def func_x(a, b=20, c=30, d=40):
    print(a, b, c, d)

def func_y(**vars):
    print(vars.values())
    
func_x(d=60, a=-10, b=-50)
# func_y(a=60)

-10 -50 30 60


In [98]:
#retirando linhas
df.drop('a', axis=0)

x         y         z
b  1.523030 -0.234153 -0.234137
c  1.579213  0.767435 -0.469474
d  0.542560 -0.463418 -0.465730
e  0.241962 -1.913280 -1.724918

In [99]:
#Seleções através de condições
df > 0 

x      y      z
a  True  False   True
b  True  False  False
c  True   True  False
d  True  False  False
e  True  False  False

In [100]:
#utilizando condição como mascara para um novo dataFrame
df[df > 0]

x         y         z
a  0.496714       NaN  0.647689
b  1.523030       NaN       NaN
c  1.579213  0.767435       NaN
d  0.542560       NaN       NaN
e  0.241962       NaN       NaN

In [101]:
#porem não salva
df

x         y         z
a  0.496714 -0.138264  0.647689
b  1.523030 -0.234153 -0.234137
c  1.579213  0.767435 -0.469474
d  0.542560 -0.463418 -0.465730
e  0.241962 -1.913280 -1.724918

In [102]:
#retira a linha do y que tem um item menor que 0
df['y']

a   -0.138264
b   -0.234153
c    0.767435
d   -0.463418
e   -1.913280
Name: y, dtype: float64

In [103]:
df.y

a   -0.138264
b   -0.234153
c    0.767435
d   -0.463418
e   -1.913280
Name: y, dtype: float64

In [104]:
df.y > 0

a    False
b    False
c     True
d    False
e    False
Name: y, dtype: bool

In [105]:
df[df.y > 0]

x         y         z
c  1.579213  0.767435 -0.469474

In [106]:
df[df.x > 0.5]

x         y         z
b  1.523030 -0.234153 -0.234137
c  1.579213  0.767435 -0.469474
d  0.542560 -0.463418 -0.465730

In [107]:
df[(df.x > 0.5) & (df.y > 0)]

x         y         z
c  1.579213  0.767435 -0.469474

In [108]:
df  > 0

x      y      z
a  True  False   True
b  True  False  False
c  True   True  False
d  True  False  False
e  True  False  False

In [109]:
#Mesma operação de cima porem so retorna o linha z
df.loc[df.y < 0, ['z']]

z
a  0.647689
b -0.234137
d -0.465730
e -1.724918

In [110]:
#resetando index
df.loc[df.y < 0, ['z']].reset_index()

index         z
0     a  0.647689
1     b -0.234137
2     d -0.465730
3     e -1.724918

In [111]:
#resetando index sem manter o index antigo
df.loc[df.y < 0, ['z']].reset_index(drop=True)

z
0  0.647689
1 -0.234137
2 -0.465730
3 -1.724918

In [112]:
df['nova'] = 1 

In [113]:
df.loc[df.x > 0.5, 'nova'] = 0
df

x         y         z  nova
a  0.496714 -0.138264  0.647689     1
b  1.523030 -0.234153 -0.234137     0
c  1.579213  0.767435 -0.469474     0
d  0.542560 -0.463418 -0.465730     0
e  0.241962 -1.913280 -1.724918     1

In [114]:
df['nova2'] = df.x.apply(lambda var: 0 if var > 0.5 else 1)
df

x         y         z  nova  nova2
a  0.496714 -0.138264  0.647689     1      1
b  1.523030 -0.234153 -0.234137     0      0
c  1.579213  0.767435 -0.469474     0      0
d  0.542560 -0.463418 -0.465730     0      0
e  0.241962 -1.913280 -1.724918     1      1

In [115]:
df.drop(['nova', 'nova2'], axis=1, inplace=True)

In [116]:
df['nomes'] = ['SP','RJ','BH','SSA','NV']

In [117]:
df

x         y         z nomes
a  0.496714 -0.138264  0.647689    SP
b  1.523030 -0.234153 -0.234137    RJ
c  1.579213  0.767435 -0.469474    BH
d  0.542560 -0.463418 -0.465730   SSA
e  0.241962 -1.913280 -1.724918    NV

In [118]:
#reordenando as colunas
df = df[['x', 'nomes', 'y', 'z']]

In [119]:
df

x nomes         y         z
a  0.496714    SP -0.138264  0.647689
b  1.523030    RJ -0.234153 -0.234137
c  1.579213    BH  0.767435 -0.469474
d  0.542560   SSA -0.463418 -0.465730
e  0.241962    NV -1.913280 -1.724918

In [120]:
#Alterando o nome das colunas
df.columns = ['x', 'estados', 'y', 'z']
df

x estados         y         z
a  0.496714      SP -0.138264  0.647689
b  1.523030      RJ -0.234153 -0.234137
c  1.579213      BH  0.767435 -0.469474
d  0.542560     SSA -0.463418 -0.465730
e  0.241962      NV -1.913280 -1.724918

In [121]:
df.rename(columns={'estados': 'estados_novos'}, inplace=True)
df

x estados_novos         y         z
a  0.496714            SP -0.138264  0.647689
b  1.523030            RJ -0.234153 -0.234137
c  1.579213            BH  0.767435 -0.469474
d  0.542560           SSA -0.463418 -0.465730
e  0.241962            NV -1.913280 -1.724918

In [122]:
df.columns

Index(['x', 'estados_novos', 'y', 'z'], dtype='object')

In [123]:
columns = df.columns.values.tolist()
columns

['x', 'estados_novos', 'y', 'z']

In [124]:
'estados_novos' in columns

True

In [125]:
columns[columns.index('estados_novos')] = 'estados'

In [126]:
df.columns = columns
df

x estados         y         z
a  0.496714      SP -0.138264  0.647689
b  1.523030      RJ -0.234153 -0.234137
c  1.579213      BH  0.767435 -0.469474
d  0.542560     SSA -0.463418 -0.465730
e  0.241962      NV -1.913280 -1.724918

In [130]:
#criando novo index
df.set_index('estados', inplace=True)

In [131]:
df

x         y         z
estados                              
SP       0.496714 -0.138264  0.647689
RJ       1.523030 -0.234153 -0.234137
BH       1.579213  0.767435 -0.469474
SSA      0.542560 -0.463418 -0.465730
NV       0.241962 -1.913280 -1.724918

In [132]:
df.loc['RJ']

x    1.523030
y   -0.234153
z   -0.234137
Name: RJ, dtype: float64

In [134]:
df.reset_index(inplace=True)

In [136]:
df

estados         x         y         z
0      SP  0.496714 -0.138264  0.647689
1      RJ  1.523030 -0.234153 -0.234137
2      BH  1.579213  0.767435 -0.469474
3     SSA  0.542560 -0.463418 -0.465730
4      NV  0.241962 -1.913280 -1.724918

In [135]:
df[df.estados == 'RJ']

estados        x         y         z
1      RJ  1.52303 -0.234153 -0.234137

In [137]:
df_estados = df.set_index('estados')
df_estados

x         y         z
estados                              
SP       0.496714 -0.138264  0.647689
RJ       1.523030 -0.234153 -0.234137
BH       1.579213  0.767435 -0.469474
SSA      0.542560 -0.463418 -0.465730
NV       0.241962 -1.913280 -1.724918

In [138]:
df

estados         x         y         z
0      SP  0.496714 -0.138264  0.647689
1      RJ  1.523030 -0.234153 -0.234137
2      BH  1.579213  0.767435 -0.469474
3     SSA  0.542560 -0.463418 -0.465730
4      NV  0.241962 -1.913280 -1.724918

**indices multiplos**

In [306]:
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [307]:
hier_index = pd.MultiIndex.from_tuples(hier_index)

hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [311]:
matriz = np.random.randn(6,2)
matriz

array([[-0.56228753, -1.01283112],
       [ 0.31424733, -0.90802408],
       [-1.4123037 ,  1.46564877],
       [-0.2257763 ,  0.0675282 ],
       [-1.42474819, -0.54438272],
       [ 0.11092259, -1.15099358]])

In [312]:
df = pd.DataFrame(matriz,index=hier_index,columns=['A','B'])

df

A         B
G1 1 -0.562288 -1.012831
   2  0.314247 -0.908024
   3 -1.412304  1.465649
G2 1 -0.225776  0.067528
   2 -1.424748 -0.544383
   3  0.110923 -1.150994

#### Concats e merges

#### Importando dados

In [314]:
filename = '../datasets/imoveis_Rio_de_Janeiro.csv'
df_imoveis_rj = pd.read_csv(filename, sep=';')
df_imoveis_rj

condominio  quartos  suites  vagas  area  bairro  atualizacao    preco  \
0            350        1     0.0    1.0    21       1            1   340000   
1            800        1     0.0    1.0    64       1            0   770000   
2            674        1     0.0    1.0    61       1            1   600000   
3            700        1     1.0    1.0    70       1            0   700000   
4            440        1     0.0    1.0    44       1            2   515000   
...          ...      ...     ...    ...   ...     ...          ...      ...   
1992        1080        3     1.0    1.0    80       7          270   680000   
1993         750        3     0.0    1.0    82       7            0   650000   
1994         700        3     1.0    1.0   100       7            0   629900   
1995        1850        3     1.0    2.0   166       7          330  1600000   
1996         800        3     1.0    1.0   107       7            0   540000   

      distancia       pm2  
0          99.0  16190.48  
1          99.0  12031.25  
2          99.0   9836.07  
3          99.0  10000.00  
4          99.0  11704.55  
...         ...       ...  
1992       99.0   8500.00  
1993       99.0   7926.83  
1994       99.0   6299.00  
1995       99.0   9638.55  
1996       99.0   5046.73  

[1997 rows x 10 columns]

In [315]:
df_imoveis_rj.suites.value_counts()

1.0    1704
2.0     135
0.0     124
3.0      34
Name: suites, dtype: int64

In [319]:
df_imoveis_rj.quartos.value_counts()

3    774
2    706
1    517
Name: quartos, dtype: int64

In [318]:
df_imoveis_rj.groupby('suites').sum()

condominio  quartos   vagas    area  bairro  atualizacao       preco  \
suites                                                                         
0.0          70765      169    97.0    7026     515         4525    77951999   
1.0        1608422     3658  1976.0  151747    6856        88483  2013792064   
2.0         195101      322   166.0   14816     537        15443   235920000   
3.0          64974      102    64.0    6244     126         2654   127468000   

        distancia          pm2  
suites                          
0.0       8925.59   1391320.98  
1.0     119025.53  22264707.56  
2.0       6259.49   2177738.20  
3.0       2479.11    639955.72

In [323]:
df_imoveis_rj.groupby(['suites', 'quartos']).agg(['sum', 'max'])

condominio        vagas        area      bairro      \
                      sum   max    sum  max    sum  max    sum max   
suites quartos                                                       
0.0    1            46737   950   72.0  1.0   4497   75    368   7   
       2            13854  1500   15.0  1.0   1241   90     83   7   
       3            10174  1190   10.0  1.0   1288  120     64   7   
1.0    1           268248  2500  426.0  3.0  20333  170   1637   7   
       2           507555  7071  649.0  3.0  48096  194   2470   7   
       3           832619  6500  901.0  4.0  83318  350   2749   7   
2.0    2           100557  4059   94.0  2.0   7447  209    322   7   
       3            94544  5400   72.0  3.0   7369  274    215   7   
3.0    3            64974  5461   64.0  4.0   6244  475    126   6   

               atualizacao            preco           distancia           \
                       sum  max         sum       max       sum      max   
suites quartos                                                             
0.0    1              3289  570    48579999   1550000   7325.05    99.00   
       2              1202  270    18413000   1600000    606.31    99.00   
       3                34   30    10959000   1350000    994.23    99.00   
1.0    1             19342  870   277200981   4000000  29152.23   972.18   
       2             28037  870   597380699   5300000  45424.32  1334.47   
       3             41104  870  1139210384  13600000  44448.98  1334.47   
2.0    2             10637  840   114873000   4200000   4234.15    99.00   
       3              4806  840   121047000   7000000   2025.34    99.00   
3.0    3              2654  630   127468000  13500000   2479.11   733.68   

                       pm2            
                       sum       max  
suites quartos                        
0.0    1        1020633.98  20857.14  
       2         252257.23  23529.41  
       3         118429.77  15000.00  
1.0    1        5976908.51  46153.85  
       2        7381887.08  48181.82  
       3        8905911.97  76666.67  
2.0    2        1334241.03  48837.21  
       3         843497.17  42500.00  
3.0    3         639955.72  45000.00